[package]
name = "witcloud"
version = "0.0.1"
edition = "2018"

[dependencies]
env_logger = "0.8.1"
common = { path = "./common"}
tokio = "*"
controller = { path = "./controller" }
gateway = { path = "./gateway" }
router = { path = "./router" }
worker = { path = "./worker" }
