[workspace]
members = [
    "cloud",
    "cloud/common",
    "cloud/router",
    "cloud/controller",
    "cloud/gateway",
    "cloud/worker",
    "cloud/worker/executor",

    "fun",
    "fun/codegen",
    "fun/runtime"
]
