[package]
name = "worker"
version = "0.1.0"
authors = ["Michal Hornicky <mhornick@redhat.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
executor = { package = "executor", path = "./executor" }
flurry = "0.3.1"
